# Скользящее среднее

# Задание
Загрузите файл в датафреймы _Pandas_ и назовите его _coderun_. Создайте в этом датафрейме столбец с датой и назовите его _date_.
Далее создайте новый датафрейм -df-, который получается в результате:

- отсечения всех дат до 01.01.2022

- группировки по дате

- расчету количества задач, решаемых в каждый день (столбец назовите problems)

- «превращение» столбца с датой из индекса в обычный столбец

А далее необходимо выполнить действия, типичные для работы, например, с временными рядами.

Очень часто временные ряды настолько зашумленные, что определить какие-то существенные паттерны довольно сложно - даже на графике. Поэтому их сглаживают.
Классический метод сглаживания - скользящее среднее.

Создайте столбец *rolling_avg*, который получается усреднения столбца _problems_ по 7 соседним измерениям. При этом усреднение происходит не по последним 7, а по:


- предыдущим 3 элементам

- текущему элементу

- следующим 3 элементам

Возникшие в результате пропуске замените на 0. Значения округлите до 2 знака после запятой.

In [32]:
import pandas as pd
from datetime import datetime

In [33]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.float_format', '{:.2f}'.format)

In [34]:
coderun = pd.read_csv('D:/GitHub_projects/Simulative_course/data/itresume-coderun.csv', encoding='1251')

In [35]:
coderun.head()

   id               created_at  problem_id  user_id  language_id
0   1  2021-04-07 06:06:20.000          13       10            3
1   2  2021-03-31 07:10:06.000          15       13            3
2   3  2021-04-04 14:55:26.000           1        6            3
3   4  2021-03-29 21:24:51.000          26        4            3
4   5  2021-03-30 11:29:12.000          21       18            3

In [36]:
coderun['date'] = pd.to_datetime(coderun['created_at']).dt.date
coderun

,id,created_at,problem_id,user_id,language_id,date
0,1,2021-04-07 06:06:20.000,13,10,3,2021-04-07
1,2,2021-03-31 07:10:06.000,15,13,3,2021-03-31
2,3,2021-04-04 14:55:26.000,1,6,3,2021-04-04
3,4,2021-03-29 21:24:51.000,26,4,3,2021-03-29
4,5,2021-03-30 11:29:12.000,21,18,3,2021-03-30
...,...,...,...,...,...,...
55717,55718,2022-05-17 09:00:51.743,101,171,2,2022-05-17
55718,55719,2022-05-17 09:01:04.210,101,171,2,2022-05-17
55719,55720,2022-05-17 09:02:06.203,101,171,2,2022-05-17
55720,55721,2022-05-17 09:03:45.265,102,171,2,2022-05-17
55721,55722,2022-05-17 09:03:57.645,102,171,2,2022-05-17

In [56]:
df = coderun[coderun['date'] >= datetime.strptime("2022-01-01", "%Y-%m-%d").date()]. \
    groupby(['date']). \
    apply(lambda x: pd.Series(data=x['problem_id'].count(), index=['problems']), include_groups=False). \
    reset_index()
df

           date  problems
0    2022-01-01        83
1    2022-01-02        26
2    2022-01-03        55
3    2022-01-04       302
4    2022-01-05       503
..          ...       ...
131  2022-05-13       369
132  2022-05-14       201
133  2022-05-15       195
134  2022-05-16       397
135  2022-05-17        78

[136 rows x 2 columns]

In [57]:
df['rolling_avg'] = df.problems.rolling(window=7, center=True).mean().round(2).fillna(0)
df

           date  problems  rolling_avg
0    2022-01-01        83         0.00
1    2022-01-02        26         0.00
2    2022-01-03        55         0.00
3    2022-01-04       302       185.86
4    2022-01-05       503       218.43
..          ...       ...          ...
131  2022-05-13       369       292.71
132  2022-05-14       201       272.43
133  2022-05-15       195         0.00
134  2022-05-16       397         0.00
135  2022-05-17        78         0.00

[136 rows x 3 columns]